# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Arnab Halder"
resume_title:                   "Student / Programmer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "harnab308@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 6296790017"
resume_contact_address:         "Basirhat, Abu Daiyan Road, Vill - Sainpala, PO & PS - Basirhat, PIN - 743411"

resume_header_contact_info:     "Basirhat, Sainpala • +91 6296790017 • harnab308@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a student, highly interested in Computer Science & Programming. I learned Python and C-Programming languages all by myself and created a few projects with those languages. Interested in further collaboration with people who have the same interest as me. 

Working on myself, building a better version of myself, learning new things, focused on building a good network of people to improve & get better.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
